plugins {
    id 'java'
    id "org.sonarqube" version "7.3.1.8318"
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'info.solidsoft.pitest' version '1.19.0'
}

group = 'app.calidad'
version = '1.0-SNAPSHOT'
description = 'API REST para reserva de espacios y recursos'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.h2database:h2'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.0.3'
    pitest 'org.junit.platform:junit-platform-launcher:6.0.3'

    testImplementation 'io.cucumber:cucumber-java:7.18.0'
    testImplementation 'io.cucumber:cucumber-spring:7.18.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.18.0'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register("acceptanceTest", Test) {
    useJUnitPlatform()
    description = "Runs Cucumber acceptance tests."
    group = "verification"
}

sourceSets.test.java.srcDir file('src/test')

pitest {
    junit5PluginVersion = '1.2.2'
    targetClasses = ['app.calidad.reservas.service.*']
    outputFormats = ['HTML', 'XML']
    timestampedReports = false
    mutationThreshold = 100
    testStrengthThreshold = 100
    verbose = true
    addJUnitPlatformLauncher = false
}

sonar {
    properties {
        property 'sonar.projectKey', 'CalidadProject'
        property 'sonar.projectName', 'Proyecto Demo Calidad'
        property 'sonar.host.url', 'http://host.docker.internal:9000'
        property 'sonar.token', System.getenv('SONAR_TOKEN')
    }
}